# Generated by Django 6.0.5 on 2026-08-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptions',
            new_name='description',
        ),
    ]
