# Generated by Django 6.0.5 on 2026-08-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_rename_descriptions_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='transaction_types',
            new_name='transaction_type',
        ),
    ]
